version: '3.8'

services:
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGO_HOST=db
      - MONGO_PORT=27017
volumes:
  data:
